#!/usr/bin/env python3
"""Generate compact linguist source-path tables (programming, markup, prose)."""

from __future__ import annotations

import datetime
import os
import re
import urllib.request

URL = "https://raw.githubusercontent.com/github-linguist/linguist/master/lib/linguist/languages.yml"
SOURCE_TYPES = {"programming", "markup", "prose"}
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def language_blocks(text: str) -> list[list[str]]:
    blocks: list[list[str]] = []
    current: list[str] = []
    for line in text.splitlines():
        if line.startswith("#") or line.strip() in {"", "---"}:
            continue
        if line and not line[0].isspace() and line.endswith(":"):
            if current:
                blocks.append(current)
            current = [line]
        elif current:
            current.append(line)
    if current:
        blocks.append(current)
    return blocks


def collect(blocks: list[list[str]]) -> tuple[list[str], list[str]]:
    extensions: set[str] = set()
    filenames: set[str] = set()
    for block in blocks:
        text = "\n".join(block)
        match = re.search(r"^\s+type:\s+(\w+)", text, re.M)
        if not match or match.group(1) not in SOURCE_TYPES:
            continue
        in_extensions = in_filenames = False
        for line in block[1:]:
            stripped = line.strip()
            if stripped.startswith("extensions:"):
                in_extensions, in_filenames = True, False
                continue
            if stripped.startswith("filenames:"):
                in_filenames, in_extensions = True, False
                continue
            if stripped.endswith(":") and not stripped.startswith("-"):
                in_extensions = in_filenames = False
                continue
            if not stripped.startswith("- "):
                continue
            item = stripped[2:].strip().strip('"').strip("'")
            if in_extensions and item.startswith("."):
                extensions.add(item.lower())
            elif in_filenames:
                filenames.add(item.lower())
    return sorted(extensions), sorted(filenames)


def write_txt(path: str, items: list[str]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(items) + "\n")


def swift_set(items: list[str]) -> str:
    inner = ",\n        ".join(
        '"' + item.replace("\\", "\\\\").replace('"', '\\"') + '"' for item in items
    )
    return "[\n        " + inner + "\n    ]"


def main() -> None:
    text = urllib.request.urlopen(URL, timeout=60).read().decode("utf-8")
    extensions, filenames = collect(language_blocks(text))
    write_txt(
        os.path.join(ROOT, "crates/jayjay-primitives/src/source_path/extensions.txt"),
        extensions,
    )
    write_txt(
        os.path.join(ROOT, "crates/jayjay-primitives/src/source_path/filenames.txt"),
        filenames,
    )
    swift_path = os.path.join(ROOT, "shell/mac/Sources/JayJay/Shared/SourcePathData.swift")
    with open(swift_path, "w", encoding="utf-8") as handle:
        handle.write(
            "/// Generated from github-linguist languages.yml (programming, markup, prose).\n"
            "/// Regenerated by scripts/gen-linguist-source-paths.py — do not edit by hand.\n"
            "enum SourcePathData {\n"
            f"    static let extensions: Set<String> = {swift_set(extensions)}\n"
            f"    static let filenames: Set<String> = {swift_set(filenames)}\n"
            "}\n"
        )
    print(f"extensions={len(extensions)} filenames={len(filenames)} date={datetime.date.today().isoformat()}")


if __name__ == "__main__":
    main()
